repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        name: (Common) Remove trailing whitespaces
      - id: mixed-line-ending
        name: (Common) Fix mixed line ending
        args: [--fix=lf]
      - id: end-of-file-fixer
        name: (Common) Remove extra EOF newlines
      - id: check-merge-conflict
        name: (Common) Check for merge conflicts
      - id: requirements-txt-fixer
        name: (Common) Sort "requirements.txt"
      - id: fix-encoding-pragma
        name: (Python) Remove encoding pragmas
        args: [--remove]
      - id: debug-statements
        name: (Python) Check for debugger imports
      - id: check-json
        name: (JSON) Check syntax
      - id: check-yaml
        name: (YAML) Check syntax
      - id: check-toml
        name: (TOML) Check syntax
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        name: (Markdown) Format docs with mdformat
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        name: (Python) Update syntax for newer versions
        args: [--py37-plus]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: (Python) Format code with black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: (Python) Sort imports with isort
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.4
    hooks:
      - id: clang-format
        name: (C/C++/CUDA) Format code with clang-format
        args: [-style=google, -i]
        types_or: [c, c++, cuda]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the version you want
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10000"]
